apiVersion: v1
kind: Service
metadata:
  name: "{{ template "stackl.core" . }}"
  labels:
    {{- include "stackl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.stacklCore.serviceType }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "stackl.selectorLabels" . | nindent 4 }}
    component: core
